classDiagram

    Reserva -->"1" Cliente
    SistemaAdministracion -->"0..*" Reserva
    Administrador -->"1" SistemaAdministracion
    Cliente --|> Persona
    Cliente -->"1..*" Chico
    Reserva "1"<--FiestaInfantil
    Reserva -->"1" EstadoPago
    FiestaInfantil -->"1..*" Chico
    FiestaInfantil -->"1" Coordinadora
    FiestaInfantil -->"1..*" JuegoParque
    Coordinadora --|> Persona
    Reserva -->"1" Carpa
    Persona -->"1" TipoDocumento
    Chico --|> Persona
    Reserva -->"1" PaqueteReserva
    Reserva -->"1" FormaPago
    Administrador
    class Reserva {
        -Date diaCumpleaños
        -Str nombreCliente
        -Str apellidoCliente
        -Str numeroTelefonoCliente
        -Int DocumentoCliente
        -TipoDocumento tipoDocumentoCliente
        -Str nombreCumpleañero
        -Str apellidoCumpleañero
        -Str edadCumpleañero
        -Int DocumentoCumpleañero
        -TipoDocumento tipoDocumentoCumpleañero
        -Int cantidadInvitados
        -Time HoraCumpleaños
        -PaqueteReserva paqueteReserva
        -Carpa CarpaSeleccionada
        -Str datosAdicionales
        -FormaPago formaPagoReserva
        -EstadoPago estadoPagoReserva
        -getDocumentoCliente()
        -getDocumentoCumpleañero()
        -CalcularTotal()
    }
    class Cliente {
        -Str numeroTelefono
        -Chico[list] hijos

        +getDocumentoCliente()
        +getDocumentoCumpleañero()
    }
    class Persona {
        -Str nombre
        -Str apellido
        -Str docmuneto
        -TipoDocumento tipoDocumento
    }
    class Carpa{
        -Int numero
    }
    class Administrador {
        -SistemaAdministracion SistemaDelAdministrador
    }
    class EstadoPago {
        -Str nombre
        -Str descripcion
    }
    class PaqueteReserva {
        -Str nombre
        -Str descripcion
        -Float precioPaquete
    }
    class TipoDocumento {
        -Str nombre
        -Str descripcion
    }
    class FiestaInfantil {
        -Chico[list] listaChicosDeFiesta
        -Coordinadora coordinadoraAsignada
        -JuegoParque[list] juegosDisponibles
        -getJuegosAcordeAEdad()
    }
    class Chico {
        -Int edad
        +esCumpleañero()
        +getDocumentoCumpleañero()
    }
    class SistemaAdministracion {
        -Reserva[list] listaReservas
    }
    class FormaPago {
        -Str nombre
        -Str descripcion
    }

    class Coordinadora

    class JuegoParque {
        -Str nombre
        -Str descripcion
        -Int edadMinima
        +esAcordeAEdad()
        +getDatosJuego()
    }